os:
  editPreset: "vscode"
promptToReturnFromSubprocess: false
customCommands:
  - key: "F"
    command: "git fetch origin -p"
    context: "localBranches"
gui:
  sidePanelWidth: 0.2
git:
  pagers:
    - colorArg: always
      pager: ~/.config/lazygit/delta-auto.sh
  autoForwardBranches: "none"
